__title__ = 'carnet'
__version__ = '0.0.1'
__description__ = 'Static website generator framework'
__author__ = 'Romain Clement'
__author_email__ = 'r.clement88@gmail.com'
__url__ = 'https://github.com/rclement/carnet'
__license__ = 'MIT'
